# Generated by Django 5.0.6 on 2024-05-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AO_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('numero_ao', models.CharField(max_length=100)),
                ('designation', models.TextField()),
                ('date_lancement', models.DateField()),
                ('date_remise', models.DateField()),
                ('date_ouverture', models.DateField()),
                ('estimation_projet_dhht', models.CharField(max_length=100)),
                ('seance_ouverture', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
            ],
        ),
    ]
