# Generated by Django 3.2.25 on 2024-05-17 13:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('AO_app', '0002_tabledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MA'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='type_of_request',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='estimation_projet_dhht',
            field=models.FloatField(),
        ),
    ]
