# Generated by Django 3.2.25 on 2024-05-17 13:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('AO_app', '0003_auto_20240517_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('activite', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MA')),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MA')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mdp', models.CharField(max_length=128)),
            ],
        ),
    ]
